project:
  type: website

website:
  title: "rafael de acypreste"
  favicon: images/icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Publications
        menu:
          - href: publications/papers.qmd
            text: Papers
          - href: publications/books.qmd
            text: Books and Chapters
          - href: publications/talks.qmd
            text: Talks and Posters  
      - text: Presentations
        menu:
          - presentations/avaliando-graficos.qmd
          - href: presentations/apresentacao-tcc.qmd
            text: Fare-Free Presentation           
      - text: R notes
        menu:
          - r-notes/r-notes-base.qmd
    logo: images/icon.png
    tools:
      - icon: twitter
        href: https://twitter.com/rafaelramr
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/rafaeldeacypreste/rafaeldeacypreste.github.io
          - text: Github Profile
            url: https://github.com/rafaeldeacypreste
      - icon: mailbox
        mailto: rafaeldeacyprestemr@gmail.com
  page-footer: "MIT License 2023, Rafael de Acypreste." 
  twitter-card: 
    creator: "@rafaelramr"
  open-graph: true

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



