project:
  type: website

website:
  title: "rafael de acypreste"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - about.qmd
      - text: Presentations
        menu:
          - presentations/presentation-demo.qmd
    logo: images/icon.png
    tools:
      - icon: twitter
        href: https://twitter.com/rafaelramr
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/rafaeldeacypreste/rafaeldeacypreste.github.io
          - text: Github Profile
            url: https://github.com/rafaeldeacypreste
      - icon: mailbox
        mailto: rafaeldeacyprestemr@gmail.com
  page-footer: "MIT License 2023, Rafael de Acypreste." 
  twitter-card: 
    creator: "@rafaelramr"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



